3 files added
Saqibi4213/my-portfolio pull request #1
Opened 2024-06-04 13:25 UTC by Saqibi4213

This is Portfolio about ME ! 
i worked on it with patient and alot of eforts 
trying to make portfolio professional and 
i worked on it with two code languages 
HTML , CSS 
linters also added

2024-06-05 09:16 UTC, Saqibi4213 commented
hello dear @fatiabdulahi please checkout if their is any thing need to add or not orr any error

2024-06-05 19:46 UTC, Saqibi4213 commented
hello dear @fatiabdulahi  please review my pull request

2024-06-06 10:36 UTC, ahzamir commented
@fatiabdulahi

- Although it's been more than 24 hours that your partner asked you for a review and feedback you did not provide feedback for them.

2024-06-06 10:54 UTC, ahzamir requested changes
### Hi @Saqibi4213 🙋‍♀️,

> Excellent work! You have done a great job implementing the project requirements but your project still misses some of the requirements:

- You have done a great job creating an amazing designed portfolio but still, your portfolio misses some of the Important requirements to be shared.
  - Check the comments below for more details.
  
# Status: Required Changes 🔁
Make changes to your code and commit and request for a re-review.

![AlmostThereReachGIF](https://github.com/LimaSahibzada/Survey-Form-project1/assets/96838030/4f0a3cd6-3a46-4e1e-8e31-ef617d4e8ac3)

 ## Highlights 🌞
 
🎯 Great Design implemented.
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
❌Your webpage is responsive for different screen sizes

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-06 10:54 UTC, ahzamir commented on index.html
> +      </div>
![Screenshot 2024-06-06 124419](https://github.com/Saqibi4213/my-portfolio/assets/96838030/b3e2032b-21e7-4461-8b0b-3b1bfbf4cb87)

- Try to add the actual and real data about your services here and also if there is any link for your services add the link (a) tag other than that you can remove them.

2024-06-06 10:54 UTC, ahzamir commented on index.html
> +      </div>
![Screenshot 2024-06-06 124436](https://github.com/Saqibi4213/my-portfolio/assets/96838030/1a5fc11e-e0dd-4302-b124-67059086680c)

- Try to add the Source Code (Your project github link) besides your Demo (Live link).

2024-06-06 10:54 UTC, ahzamir commented on style.css
![Screenshot 2024-06-06 124343](https://github.com/Saqibi4213/my-portfolio/assets/96838030/a9911185-700a-4c3b-b6d6-80b4148faec6)

- Although your design is impressive, your webpage is not responsive and does not look great on smaller screens like the mobile version.
  - Try to make your webpage responsive using media query.

2024-06-06 16:40 UTC, fatiabdulahi commented
> This is Portfolio about ME ! i worked on it with patient and alot of eforts trying to make portfolio professional and i worked on it with two code languages HTML , CSS linters also added and deployed link added live link also mentioned my partner to review my repo and project

2024-06-06 16:41 UTC, fatiabdulahi commented
@Saqibi4213 hello dear @Saqibi4213 your work is very well excellent

2024-06-06 20:03 UTC, Saqibi4213 commented on style.css
hello sir can you please give me brief advice and where is the problem i cant undrenstand i used to try mobile version to make my mobile version responsive too but in screenshot where is the exact problem i cant undrestand

2024-06-06 21:03 UTC, Saqibi4213 commented
Hello Sir @ahzamir please Review my repo and project 
source link added 
cv download added 
responsive try to make it better 
please if thier is anything left or wrong again give me feedback  thank you

2024-06-07 17:19 UTC, Saqibi4213 commented
Hello Sir @ahzamir please Review my repo and project
source link added
cv download added
responsive try to make it better
please if their is anything left or wrong again give me feedback thank you

2024-06-08 13:58 UTC, ahzamir approved these changes
### Hi @Saqibi4213 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text on it with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
![image](https://github.com/Saqibi4213/my-portfolio/assets/96838030/87617b97-fdc7-4689-b07c-734754d816b2)

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

![GreatJobThumbsUpGIF](https://github.com/ZuhRa-HashiMi/survey-form/assets/96838030/cc459d3f-5796-43f0-aba7-4ed0c35fa276)

 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Capstone project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your project has a professional README.md file

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me @ahzamir in your question so I can receive the notification.**

2024-06-08 14:00 UTC, ahzamir commented
@Saqibi4213 

- Deploy your project after you merged this pull-request
- Well done mehria, don't forget to share your success on the FB group and your LinkedIn profile as this is mandatory.

2024-06-08 15:16 UTC, merged

2024-06-09 12:04 UTC, fatiabdulahi commented on style.css
you are work good  dear excellent